language: python
dist: xenial
python:
- '3.6'
- '3.7'
- "3.8-dev"
install:
- pip install -U coveralls pytest
script:
- coverage run --source=domdf_spreadsheet_tools -m pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: "DomDF"
  password:
    secure: UrEhUVL+wymxE48XesC6utHtlLMNoLStOMQS7c/z/7+HzSMoBWjBb6HzrJwullC1VQarNElyfffz49kzlygp+sneV8m9YEengOZZPkzCjjOty0trJi8JIqAAlwQ8EXVeltBwfl06eI6ij93FsGKpduX/w2Lrlzsm6QM6Lu7wSkyISQKguxvOO5eQ6LyofqAtXcvBzpXubTamaBYtooX95le19u4+btVKomDtRVmGwzghDXBM6u/sGhnVU78Xtva0xxN22WXXLNc8iDd5pXCRBSJzGPbRcnxgFqyzsjEJ/8VklTB+hu014ORw2HNGtOP71+viCFsiQRg2PMnrr31obJfQmAVvICX02mDLbFQi/8ma2X7tpR4yGnRabLdVrgZF0JsCEZPigxRUIOlD2PJWwjgj8Mtq4OH1SZrPDWKx0iFe/N90JM3Ej5hf5dxTlEV778es2CGLE5R1AYZBdUaHKeGEI1c93VagDZaegwotI5/QMQ8kCu+Nf6W2rnE0tT4OTlmUSqKFjd5MV4ZUHG080M1/J4YckwWAqNMEegqq6OuWTwoeXNxA48xre9pePd8Dj5F+Tl2gW5ZR6wcyfiPRpHspQ6MagDixLwMgTUvT6S+os0/7sGvLu0WhXBZcR5YU2rbX20CeoFoGANX3y6FvND4Ty73xRb3W8LaF5KV7Ha8=
  on:
    tags: true
    python: '3.6'
  distributions: "sdist bdist_wheel"
  skip_existing: True
